-- 코드를 입력하세요
WITH RECURSIVE hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM hours WHERE HOUR < 23
)

SELECT H.HOUR ,IFNULL(COUNT(A.DATETIME),0) AS COUNT
FROM ANIMAL_OUTS AS A RIGHT JOIN hours AS H 
ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR 
ORDER BY H.HOUR 
