-- 코드를 입력하세요
WITH AVAI AS (SELECT 
              CASE WHEN END_DATE < '2022-10-16' THEN "대여 가능"
             WHEN END_DATE >= '2022-10-16' AND START_DATE <='2022-10-16' THEN "대여중"
             ELSE "대여 가능"
        END AS AVAILABILITY,CAR_ID,START_DATE
        ,END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC),
N AS (SELECT CAR_ID,AVAILABILITY
FROM AVAI
WHERE AVAILABILITY	= "대여중"
GROUP BY CAR_ID),
Y AS(
    SELECT CAR_ID,"대여 가능" AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID NOT IN (SELECT CAR_ID FROM N)
)

(select *
from N)
union
(select *
 from Y
)
ORDER BY CAR_ID	DESC


