WITH RECURSIVE TABL AS (
    SELECT ID,1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID is null
    
    UNION
    
    SELECT E.ID,T.GENERATION +1
    FROM ECOLI_DATA  AS E, TABL AS T
    WHERE E.PARENT_ID = T.ID
)

SELECT COUNT(*) AS COUNT,GENERATION
FROM ECOLI_DATA AS E INNER JOIN TABL AS T
ON E.ID = T.ID
WHERE E.ID NOT IN (SELECT IFNULL(PARENT_ID,0)
                 FROM ECOLI_DATA)
GROUP BY GENERATION