-- 코드를 입력하세요
SELECT A.AUTHOR_ID,AUTHOR_NAME,CATEGORY,SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK AS B INNER JOIN BOOK_SALES AS S INNER JOIN AUTHOR AS A
ON B.BOOK_ID = S.BOOK_ID AND A.AUTHOR_ID = B.AUTHOR_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY A.AUTHOR_ID,CATEGORY
ORDER BY A.AUTHOR_ID,CATEGORY DESC