-- 코드를 작성해주세요
SELECT CASE WHEN GROUP_CONCAT(CATEGORY) LIKE "%Front End%" AND GROUP_CONCAT(NAME) LIKE "%Python%" THEN "A"
WHEN GROUP_CONCAT(NAME) LIKE "%C#%" THEN "B"
WHEN GROUP_CONCAT(CATEGORY) LIKE "%Front End%" THEN "C"
END AS GRADE,ID,EMAIL
FROM DEVELOPERS JOIN SKILLCODES
ON (SKILL_CODE & CODE) >0
GROUP BY ID,EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE,ID