-- 코드를 작성해주세요
with new as (
    SELECT MAX(LENGTH) as LENGTH,FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE 
)

select ID,FISH_NAME,FISH_INFO.LENGTH
from FISH_INFO,new,FISH_NAME_INFO
where FISH_INFO.LENGTH =  new.LENGTH and  FISH_INFO.FISH_TYPE = new.FISH_TYPE and FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
order by id
# SELECT id,fish_name,MAX(LENGTH) 
# FROM FISH_INFO INNER JOIN FISH_NAME_INFO
# ON FISH_INFO.FISH_TYPE = FISH_N
# order by id